src/aashe_bulletin/urls.py
import django.contrib.auth.views
from django.conf.urls import patterns, include, url
from django.contrib import admin
from bulletin.tools.plugins.views.story import StoryListView

from views import (AllItemsView,
                   FAQView,
                   LatestNewsFeedView,
                   NoSearchForYouView,
                   SubmissionGuidelinesView)

admin.autodiscover()

urlpatterns = patterns(
    '',

    url(r'^$',
        StoryListView.as_view(),
        name='front-page'),

    url(r'^all-items/$',
        AllItemsView.as_view(),
        name='all-items'),

    url(r'^accounts/login/$',
        django.contrib.auth.views.login,
        name="login"),

    url(r'^accounts/logout/$',
        django.contrib.auth.views.logout,
        name="logout"),

    url(r'^help/',
        FAQView.as_view(),
        name='faq'),

    url(r'^submission-guidelines/',
        SubmissionGuidelinesView.as_view(),
        name='submission-guidelines'),

    url(r'^search-permission-denied/',
        NoSearchForYouView.as_view(),
        name='no-search-for-you'),

    url(r'^admin/',
        include(admin.site.urls)),

    url(r'^flat-pages/',
        include('django.contrib.flatpages.urls')),

    url(r'^rss/news/$',
        LatestNewsFeedView(),
        name='latest-news-feed'),

    url(r'^rss/news/category/(?P<category>.+)/$',
        LatestNewsFeedView(),
        name='latest-news-category-feed'),

    url(r'^',
        include('bulletin.urls',
                namespace='bulletin')),
)

src/aashe_bulletin/views.py
from braces.views import SetHeadlineMixin
from django.contrib.syndication.views import Feed
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.utils.http import urlunquote
from django.views.generic import TemplateView

from bulletin import views as bulletin_views
from bulletin.models import Category
from bulletin.tools.plugins.models import Story


class AllItemsView(bulletin_views.FrontPageView,
                   bulletin_views.SidebarView):

    template_name = 'all_items.html'
    headline = 'All Items'


class FAQView(SetHeadlineMixin,
              bulletin_views.SidebarView,
              TemplateView):

    headline = 'Frequently Asked Questions'
    template_name = 'faq.html'


class LatestNewsFeedView(Feed):

    def get_object(self, request, category=None):
        if category:
            return get_object_or_404(Category,
                                     name__iexact=urlunquote(category))
        return None

    def title(self, obj):
        if obj is not None:
            return 'AASHE Bulletin ' + obj.name + ' News'
        else:
            return 'AASHE Bulletin News'

    def description(self, obj):
        if obj is not None:
            return ('Latest ' + obj.name.lower() +
                    ' news from the AASHE Bulletin.')
        else:
            return 'Latest news from the AASHE Bulletin.'

    def link(self, obj):
        if obj is not None:
            return reverse('latest-news-category-feed',
                           kwargs={'category': obj.name})
        else:
            return reverse('latest-news-feed')

    def items(self, obj):
        qs = Story.objects.filter(approved=True).order_by('-pub_date')
        if obj is not None:
            qs = qs.filter(categories__in=[obj])
        return qs[:30]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.blurb

    def item_link(self, item):
        return item.url


class NoSearchForYouView(TemplateView):

    template_name = 'no_search_for_you.html'


class SubmissionGuidelinesView(SetHeadlineMixin,
                               bulletin_views.SidebarView,
                               TemplateView):

    headline = 'Submission Guidelines'
    template_name = 'submission_guidelines.html'

src/aashe_bulletin/templates/all_items.html
{% extends "base.html" %}
{% load bootstrap_pagination %}

{% block front_page_tab_class %}
  active
{% endblock %}

{% block before_headline %}
  <a class="btn-u btn-u-blue btn-block visible-xs"
     href="{% url 'bulletin:plugins:plugin-list' %}?next={{ request.path }}"
     type="button">
    Submit an Item
  </a>
  <a class="btn-u btn-u-blue btn-block btn-u-lg visible-s hidden-xs"
     href="{% url 'bulletin:plugins:plugin-list' %}?next={{ request.path }}"
     type="button">
    Submit an Item
  </a>
{% endblock %}

{% block content %}
  <div class="row blog-page">
    <!-- Left Sidebar -->
    <div class="col-md-9 md-margin-bottom-40">
      {% for post in object_list %}
        <!--Post-->
        <div class="row blog blog-medium margin-bottom-40">
          <div class="col-sm-3 text-right">
            {% if post.image %}
              <img class="img-responsive" src="{{ post.image.url }}" />
            {% endif %}
          </div>
          <div class="col-sm-9">
            <a href="{{ post.url }}">
              <h2>{{ post.title }}</h2>
            </a>
            <div class="margin-bottom-10">
              {{ post.blurb|safe }}
            </div>
            <ul class="list-unstyled list-inline blog-info">
              <li><span class="glyphicon glyphicon-calendar"></span>
                {{ post.pub_date|date:"M j, Y" }}
              </li>
              {% if post.category %}
                <li><span class="glyphicon glyphicon-tag"></span>
                  {{ post.category }}
                </li>
              {% endif %}
              {% if user.is_staff %}
                <li>
                  <a href="{% url "bulletin:plugins:update" post.content_type.model post.id %}?next={{ request.get_full_path }}">
                    <span class="glyphicon glyphicon-pencil"></span>
                  </a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
        <!--End Post-->
      {% endfor %}
    </div>
    <!-- End Left Sidebar -->

    {% include "bulletin/sidebar.html" %}

    <!--Pagination-->
    <div class="text-center">
      {% bootstrap_paginate page_obj range=10 show_first_last="true" %}
    </div>
    <!--End Pagination-->

  </div><!--/row-->
{% endblock %}

src/aashe_bulletin/templates/bulletin/thank_you_for_submitting_post.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4>Thank you!</h4>
    </div>
    <div class="panel-body">
      {% block thank_you %}
        <p>
          Thank you for your submission to the AASHE Bulletin website.
          Please allow 48 business hours for review.
        </p>
      {% endblock %}
      <a type="button"
         href="{{ next }}"
         class="btn btn-primary">
        Continue
      </a>
    </div>
  </div>
{% endblock content %}

src/aashe_bulletin/templates/css.html
{% load static from staticfiles %}
{% comment %}

This is the HTML to pull the main CSS for the bulletin project.
It's pulled out into its own file so it can be shared between
templates for the web site and templates for newsletter issues.

{% endcomment %}

<!-- START of css.html -->

<!-- CSS Global Compulsory -->
<link rel="stylesheet"
      href="{% static "theme/assets/plugins/bootstrap/css/bootstrap.css" %}" />
<link rel="stylesheet"
      href="{% static "assets/css/base.css" %}" />
<link rel="stylesheet"
      href="{% static "theme/assets/css/style.css" %}" />
<link rel="stylesheet"
      href="{% static "assets/css/headers/header1.css" %}" />
<link rel="stylesheet"
      href="{% static "assets/css/responsive.css" %}" />
<link rel="shortcut icon"
      href="{% static "favicon.ico" %}" />

<!-- CSS Implementing Plugins -->
<link rel="stylesheet"
      href="{% static "theme/assets/plugins/font-awesome/css/font-awesome.css" %}" />

<!-- CSS Page Style -->
<link rel="stylesheet"
      href="{% static "theme/assets/css/pages/blog.css" %}" />
<link rel="stylesheet"
      href="{% static "assets/css/pages/page_magazine.css" %}" />

<!-- CSS Theme -->
<link rel="stylesheet"
      href="{% static "theme/assets/css/theme-colors/default.css" %}"
      id="style_color" />

<!-- END of css.html -->

src/aashe_bulletin/templates/email_templates/beta_lists.html
{% load staticfiles %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
 "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en"
      xml:lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cctd="http://www.constantcontact.com/cctd">
  <head>
    <title>The Bulletin, by AASHE</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    {% include "css.html" %}  <!-- CSS shared between website and email -->
    <link rel="stylesheet" type="text/css"
          href="{% static "assets/css/email_style.css" %}">
  </head>
  <body>
    <table width="100%">
      <div id="header" class="header margin-bottom-10">
        <tr>
          <td>
            <a class="logo" href="{% url "newsletter:front-page" %}">
              <img id="logo-header"
                   src="{% static "img/bulletin_logo_words_only.png" %}"
                   alt="Logo" />
            </a>
          </td>
        </tr>
        <tr>
          <td>
            <p class="pub-date">
              {{ issue.pub_date }}
            </p>
          </td>
        </tr>
      </div> <!-- header -->

      {% if issue.introduction %}
        <tr>
          <td>
            <p class="introduction">
              {{ issue.introduction }}
            </p>
          </td>
        </tr>
      {% endif %}

      <tr>
        <td>
          {% if issue.sections.count %}
            <ul class="section-list">
              {% for section in issue.sections.all %}
                <li>
                  <div class="section-name headline">
                    <h2>
                      {{ section.name }}
                    </h2>
                  </div>

                  {% if section.posts.count %}
                    <ul class="post-list">
                      {% for post in section.posts.all %}
                        <!--Post-->
                        <li class="post">
                          <div class="post-headline headline">
                            <a href="{{ post.url }}">
                              <h4>
                                {{ post.headline }}
                              </h4>
                            </a>
                          </div>

                          <p class="post-date">
                            {{ post.post_date|date:"M j, Y" }}
                          </p>
                          {% if post.category %}
                            <p class="post-category">
                              {{ post.category }}
                            </p>
                          {% endif %}
                          <div class="post-body">
                            {{ post.body }}
                          </div>
                          {% if post.links.count %}
                            <div class="post-links">
                              <p>
                                Also see:
                              </p>
                              <ul>
                                {% for link in post.links.all %}
                                  <li>
                                    <a href="{{ link.url }}">
                                      {{ link.text }}
                                    </a>
                                  </li>
                                {% endfor %}
                              </ul>
                            </div>
                          {% endif %}
                        </li>
                        <!--End Post-->
                      {% endfor %}
                    </ul>
                  {% endif %}
                </li>
              {% endfor %}
            </ul>
          {% endif %}
        </td>
      </tr>
    </table>
  </body>
</html>

src/aashe_bulletin/templates/email_templates/beta_tables.html
{% load staticfiles %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
 "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en"
      xml:lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cctd="http://www.constantcontact.com/cctd">
  <head>
    <title>The Bulletin, by AASHE</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    {% include "css.html" %}  <!-- CSS shared between website and email -->
    <link rel="stylesheet" type="text/css"
          href="{% static "assets/css/email_style.css" %}">
  </head>
  <body>
    <table width="100%">
      <div id="header" class="header">
        <tr>
          <td align="center">
            <a class="logo" href="{% url "newsletter:front-page" %}">
              <img id="logo-header"
                   src="{% static "img/bulletin_logo_words_only.png" %}"
                   alt="Logo" />
            </a>
          </td>
        </tr>
        <tr>
          <td>
            <p class="pub-date">
              {{ issue.pub_date }}
            </p>
          </td>
        </tr>
      </div> <!-- header -->

      {% if issue.introduction %}
        <tr>
          <td>
            <p class="introduction">
              {{ issue.introduction }}
            </p>
          </td>
        </tr>
      {% endif %}

      <tr>
        <td>
          {% if issue.sections.count %}
            {% for section in issue.sections.all %}
              <!-- Section -->
              <table id="xxx" class="xxx">
                <tr>
                  <td>
                    <div class="section-name headline">
                      <h3>
                        {{ section.name }}
                      </h3>
                    </div>
                  </td>
                </tr>

                {% if section.posts.count %}
                  {% for post in section.posts.all %}
                    <!-- Post -->
                    <table class="post">
                      <tr>
                        <td>
                          <div class="post-headline headline">
                            <a href="{{ post.url }}">
                              <h4>
                                {{ post.headline }}
                              </h4>
                            </a>
                          </div>
                        </td>
                      </tr>

                      <tr>
                        <td>
                          <div class="post-date-category">
                            {{ post.post_date|date:"M j, Y" }}
                            {% if post.category %}
                              -
                              {{ post.category }}
                            {% endif %}
                          </div>
                        </td>
                      </tr>

                      <tr>
                        <td>
                          <div class="post-body">
                            {{ post.body }}
                          </div>
                        </td>
                      </tr>

                      {% if post.links.count %}
                        <tr>
                          <td>
                            <div class="post-links">
                              Also see:
                              {% for link in post.links.all %}
                                <a href="{{ link.url }}">
                                  {{ link.text }}</a>{% if not forloop.last %},
                                  {% endif %}
                              {% endfor %}
                            </div>
                          </td>
                        </tr>
                      {% endif %}
                    </table>
                    <!-- End Post -->
                  {% endfor %}
                {% endif %}
              </table>
              <!-- End Section -->
            {% endfor %}
          {% endif %}
        </td>
      </tr>
    </table>
  </body>
</html>

src/aashe_bulletin/templates/email_templates/delta.html
{% load staticfiles %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
 "http://www.w3.org/TR/html4/loose.dtd">
<html lang="en"
      xml:lang="en"
      xmlns="http://www.w3.org/1999/xhtml"
      xmlns:cctd="http://www.constantcontact.com/cctd">
  <head>
    <title>The Bulletin, by AASHE</title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width"/>

    <link rel="stylesheet" type="text/css"
          href="{% static "assets/css/ink.css" %}"> <!-- For testing only -->

    <style type="text/css">

      /* Ink styles go here in production */

    </style>
    <style type="text/css">

      /* Your custom styles go here */

    </style>
    {% include "css.html" %}  <!-- CSS shared between website and email -->
    <link rel="stylesheet" type="text/css"
          href="{% static "assets/css/email_style.css" %}">

  </head>
  <body>
    <table class="body">
      <tr>
        <td class="center" align="center" valign="top">
          <center>

            <table class="row header">
              <tr>
                <td class="center" align="center">
                  <center>

                    <table class="container">
                      <tr>
                        <td class="wrapper last">



                          <table class="twelve columns">
                            <tr>
                              <td align="center" class="last">
                                <a class="logo" href="{% url "bulletin:front-page" %}">
                                  <img id="logo-header"
                                       src="{% static "img/bulletin_logo_words_only.png" %}"
                                       alt="Logo" />
                                </a>
                              </td>
                              <td class="expander"></td>
                            </tr>
                            <tr>
                              <td align="center">
                                <p class="pub-date last">
                                  {{ issue.pub_date }}
                                </p>
                              </td>
                              <td class="expander"></td>
                            </tr>
                          </table>

                          <!--
                          <table class="twelve columns">
                            <tr>
                              <td class="six sub-columns">
                                <img src="http://placehold.it/200x50">
                              </td>
                              <td class="six sub-columns last" style="text-align:right; vertical-align:middle;">
                                <span class="template-label">SIDEBAR HERO</span>
                              </td>
                              <td class="expander"></td>
                            </tr>
                          </table>
                          -->

                        </td>
                      </tr>
                    </table>

                  </center>
              </td>
              </tr>
            </table>

            <br>

            <table class="container">
              <tr>
                <td>

                  <!-- content start -->
                  <table class="row">
                    <tr>
                      <td class="wrapper last">

                        <table class="twelve columns">
                          <tr>
                            <td>
                              <h1>Welcome, Daneel Olivan</h1>
                              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et.</p>

                            </td>
                            <td class="expander"></td>
                          </tr>
                        </table>

                        <table class="twelve columns">
                          <tr>
                            <td class="panel">
                              <p>Phasellus dictum sapien a neque luctus cursus. Pellentesque sem dolor, fringilla et pharetra vitae. <a href="#">Click it! »</a></p>
                            </td>
                            <td class="expander"></td>
                          </tr>
                        </table>

                      </td>
                    </tr>
                  </table>

                  <br>  <!-- Break Tag for row -->

                  <table class="row">
                    <tr>
                      <td class="wrapper">

                        <table class="six columns">
                          <tr>
                            <td>

                              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. Lorem ipsum dolor sit amet.</p>

                              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. Lorem ipsum dolor sit amet.</p>

                              <table class="button">
                                <tr>
                                  <td>
                                <a href="#">Click Me!</a>
                                  </td>
                                </tr>
                              </table>

                            </td>
                            <td class="expander"></td>
                          </tr>
                        </table>

                      </td>
                      <td class="wrapper last">

                        <table class="six columns">
                          <tr>
                            <td class="panel">
                              <h6>Header Thing</h6>
                              <p>Sub-head or something</p>
                              <table>
                                <tr>
                                  <td>
                                    <a href="#">Just a Plain Link &raquo;</a>
                                  </td>
                                </tr>
                              </table>
                              <hr>
                              <table>
                                <tr>
                                  <td>
                                    <a href="#">Just a Plain Link &raquo;</a>
                                  </td>
                                </tr>
                              </table>
                            <hr>
                            <table>
                              <tr>
                                <td>
                                  <a href="#">Just a Plain Link &raquo;</a>
                                </td>
                              </tr>
                            </table>
                            <hr>
                            <table>
                              <tr>
                                <td>
                                  <a href="#">Just a Plain Link &raquo;</a>
                                </td>
                              </tr>
                            </table>
                            <hr>
                            <table>
                              <tr>
                                <td>
                                  <a href="#">Just a Plain Link &raquo;</a>
                                </td>
                              </tr>
                            </table>
                            <hr>
                            <table>
                              <tr>
                                <td>
                                  <a href="#">Just a Plain Link &raquo;</a>
                                </td>
                              </tr>
                            </table>
                            <hr>
                            <table>
                              <tr>
                                <td>
                                  <a href="#">Just a Plain Link &raquo;</a>
                                </td>
                              </tr>
                            </table>
                            </td>
                            <td class="expander"></td>
                          </tr>
                        </table>
                        <br>
                        <table class="six columns">
                          <tr>
                            <td class="panel">
                              <h6 style="margin-bottom:5px;">Connect With Us:</h6>
                              <table class="tiny-button facebook">
                                <tr>
                                  <td>
                                    <a href="#">Facebook</a>
                                  </td>
                                </tr>
                              </table>

                              <hr>

                              <table class="tiny-button twitter">
                                <tr>
                                  <td>
                                    <a href="#">Twitter</a>
                                  </td>
                                </tr>
                            </table>

                            <hr>

                            <table class="tiny-button google-plus">
                              <tr>
                                <td>
                                  <a href="#">Google +</a>
                                </td>
                              </tr>
                            </table>
                            <br>
                            <h6 style="margin-bottom:5px;">Contact Info:</h6>
                            <p>Phone: <b>408.341.0600</b></p>
                            <p>Email: <a href="mailto:hseldon@trantor.com">hseldon@trantor.com</a></p>
                            </td>
                            <td class="expander"></td>
                          </tr>
                        </table>

                      </td>
                    </tr>
                  </table>
                  <br>
                  <br>
                  <!-- Legal + Unsubscribe -->
                  <table class="row">
                    <tr>
                      <td class="wrapper last">

                        <table class="twelve columns">
                          <tr>
                        <td align="center">
                          <center>
                            <p style="text-align:center;"><a href="#">Terms</a> | <a href="#">Privacy</a> | <a href="#">Unsubscribe</a></p>
                          </center>
                        </td>
                        <td class="expander"></td>
                          </tr>
                        </table>

                      </td>
                    </tr>
                  </table>

                  <!-- container end below -->
                </td>
              </tr>
            </table>

          </center>
        </td>
      </tr>
    </table>
  </body>
</html>

src/aashe_bulletin/templates/no_search_for_you.html
{% extends 'base.html' %}

{% block content %}
  <div class="well margin-bottom-40 text-center">
    Sorry, searching The Bulletin is restricted to AASHE members only.
  </div>
{% endblock %}

src/aashe_bulletin/templates/plugins/plugin_list.html
{% overextends "plugins/plugin_list.html" %}

{% block intro %}
  <div class="row">
    <div class="col-md-12 md-margin-bottom-40">
      <p>
        We gratefully accept a number of types of submissions.
      </p>
      <p>
        Our submission guidelines can be reviewed
        <a href="{% url "submission-guidelines" %}">
          here</a>.
    </div>
  </div>
{% endblock intro %}